#!/usr/bin/env bash
#a Bash script that configures the container to fit the above requirements
sudo service nginx stop
sudo pkill apache2

sudo sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf

sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[::\]:80/listen \[::\]:8080/' /etc/nginx/sites-available/default

sudo nginx -t

sudo service nginx start

